#!/bin/bash

# 1 nom du PROJECT
# 2 message du tag créé lors du déploiement 
# 
# Author : claude.billon@gmail.com
#
# This software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# It is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details

if [ $1 == '-h' ]  || [ $1 == '--help' ];
then
   printf " 1 nom du PROJECT \n"
   exit
fi

ERROR=0

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as normal user" 
   ERROR=1
fi
. ./$1.cnf || exit "unable to load ${1}" 

cd $RACINE/backup/db
numfiles=(*)
numfiles=${#numfiles[@]}
# nb versions conservées numfiles 
((numfiles=numfiles-1))

# on récuprer l'avant derniere 
RET=$(ls -t  |tail -n $numfiles | xargs rm -r)
echo $RET

ls - l $RACINE/backup/db

. ./$1.cnf || exit "unable to load ${1}" 

cd $RACINE/services/web/$PROJECT/releases
numfiles=(*)
numfiles=${#numfiles[@]}
# nb versions conservées numfiles 
((numfiles=numfiles-1))

# on récuprer l'avant derniere 
RET=$(ls -t  |tail -n $numfiles | xargs rm -r)
echo $RET
ls -l

echo "That's All!"
exit 0